<html>
<head>
<link rel="stylesheet" type="text/css" href="main.css" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
</head>

<body>
	<div class="one">
    <strong>聚会助手(party helper)-Jackling</strong>
    <br/>
	</div>
    
   

	<div class="two">
	<hr/>
	<form name="input" action="page2.php" method="get">
	<fieldset>
        <legend style="font-size:50px;"><strong>聚会时间,meeting time</strong></legend>
    时间一,time1（必填）: 
        <input type="text"  size="60" style="height:30px " name="time_1" />
    <br />
    时间二,time2（可选）: 
    <input type="text"  size="60" style="height:30px " name="time_2" />
    <br />
    时间三,time3（可选）: 
    <input type="text"  size="60" style="height:30px " name="time_3" />
    </fieldset>
    
    <br/>
    
    <fieldset>
        <legend style="font-size:50px;"><strong>聚会地点,meeting address</strong></legend>
    地点一,address1（必填）: 
    <input type="text"  size="60" style="height:30px " name="add_1" />
    <br/>
    地点二,address2（可选）: 
    <input type="text"  size="60" style="height:30px " name="add_2" />
    <br />
    地点三,address3（可选）: 
    <input type="text"  size="60" style="height:30px " name="add_3" />
    </fieldset>

    <br/>
     <?php
   $id = rand(1000,9999); 
   echo "房间号(由系统生成请勿修改),room number is generated by system, please don't change：<input type=\"text\" size=\"60\" value=$id style=\"height:30px\" name=\"id\">"
    ?>
        <br/>
    <a href="<?php echo "page2.php?id=".$room_id; ?>"><input type="submit" value="提交,submit" style="font-size:30px; width: 280px; height: 80px;"/></a>
    </form>   
    
    </div>

    
</body>
</html>