<html>
<link rel="stylesheet" type="text/css" href="main.css" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<body>
  <div class="one">
    <strong>聚会助手(party helper)-Jackling</strong>
    <br/>
  </div>

<div class="two">
    
<form name="input" action="page3.php" method="get">
<hr/>

<fieldset>
    <legend style="font-size:50px;"><strong>聚会时间,meeting time</strong></legend>
<?php
   $time_1=$_GET["time_1"];
   echo $time_1;  
?>:
<input type="checkbox" name="choose_t1" style="zoom: 200%"/>

<br/>
<?php
   $time_2 = $_GET["time_2"];
   if($time_2 != null)
   {
   echo $time_2;
   echo ":";
   echo "<input type=\"checkbox\" name=\"choose_t2\" style=\"zoom: 200%\"><br/>";
   }
   else { $time_2 = '0';}

   $time_3 = $_GET["time_3"];
   if($time_3 != null)
   {
   echo $time_3;
   echo ":";
   echo "<input type=\"checkbox\" name=\"choose_t3\" style=\"zoom: 200%\"><br/>";
   }
   else { $time_3 = '0';}
?>

</fieldset>
    
<br/>
    
<fieldset>
    <legend style="font-size:50px;"><strong>聚会地点,meeting address</strong></legend>
<?php
   $add_1=$_GET["add_1"];
   echo $add_1;
?>:
<input type="checkbox" name="choose_a1"  style="zoom: 200%"/>

<br />
<?php
   $add_2 = $_GET["add_2"];
   if($add_2 != null)
   {
   echo $add_2;
   echo ":";
   echo "<input type=\"checkbox\" name=\"choose_a2\" style=\"zoom: 200%\"><br/>";
   }
   else { $add_2 = '0';}

   $add_3 = $_GET["add_3"];
   if($add_3 != null)
   {
   echo $add_3;
   echo ":";
   echo "<input type=\"checkbox\" name=\"choose_a3\" style=\"zoom: 200%\"><br/>";
   }
   else { $add_3 = '0';}

?> 
</fieldset>
 <?php
     $room_id=$_GET["id"];
     echo "房间号(由系统生成请勿修改),room number is generated by system, please don't change<input type=\"text\" name=\"id\" value=$room_id style=\"zoom: 200%\"><br/>";
?>   


<br />
    <a href="page3.php?"><input type="submit" value="提交,submit" style="font-size:30px; width: 280px; height: 80px;"/></a>

 </form> 
</div>
    
</body>
</html>

<?php
//process data and send them to the database
 include 'conn_sql.php';
$sql = "insert into party_data(room_num,msg_type,p_time_1,p_time_2,p_time_3,p_add_1,p_add_2,p_add_3)values($room_id,'0','$time_1','$time_2','$time_3','$add_1','$add_2','$add_3')"; 
mysql_query($sql,$conn);  
mysql_close($conn);
 ?>

